name: Jekyll Build Pages

on:
          push:
                      branches:
                                    - main

                      jobs:
                                build:
                                            runs-on: ubuntu-latest

                                                steps:
                                                              - name: Checkout repository
                                                                        uses: actions/checkout@v2

                                                                              - name: Run Jekyll build
                                                                                        uses: actions/jekyll-build-pages@v1
                                                                                                with:
                                                                                                                  source: .
                                                                                                                            destination: ./_site
                                                                                                                                      future: false
                                                                                                                                                build_revision: ${{ github.sha }}
                                                                                                                                                          verbose: true
                                                                                                                                                                    token: ${{ secrets.PAT_TOKEN }}
